[www]
user = www
group = www
listen = 127.0.0.1:9000
listen.owner = www
listen.group = www

pm = dynamic
pm.max_children = 20
pm.start_servers = 4
pm.min_spare_servers = 2
pm.max_spare_servers = 6
pm.max_requests = 1000

; Log to stderr (Docker collects it)
php_admin_value[error_log] = /dev/stderr
php_admin_flag[log_errors] = On

; Security
php_flag[display_errors] = Off
php_admin_value[open_basedir] = /var/www/html:/tmp
